import Foundation
import SwiftUI

enum AppLanguage: String, CaseIterable {
    case system
    case en
    case zhHans = "zh-Hans"
    case zhHant = "zh-Hant"

    var displayName: String {
        switch self {
        case .system: return LocalizationService.shared.tr("lang_system")
        case .en: return "English"
        case .zhHans: return "简体中文"
        case .zhHant: return "繁體中文"
        }
    }

    static var systemLanguage: AppLanguage {
        let preferred = Locale.preferredLanguages.first ?? "en"
        if preferred.hasPrefix("zh-Hans") || preferred.hasPrefix("zh-CN") || preferred.hasPrefix("zh-SG") {
            return .zhHans
        }
        if preferred.hasPrefix("zh-Hant") || preferred.hasPrefix("zh-TW") || preferred.hasPrefix("zh-HK") {
            return .zhHant
        }
        return .en
    }

    var effectiveLanguage: AppLanguage {
        if self == .system { return Self.systemLanguage }
        return self
    }
}

class LocalizationService: ObservableObject {
    static let shared = LocalizationService()

    var currentLanguage: AppLanguage {
        get { _currentLanguage }
        set {
            DispatchQueue.main.async { [weak self] in
                self?._currentLanguage = newValue
                UserDefaults.standard.set(newValue.rawValue, forKey: "app_language")
            }
        }
    }
    @Published var _currentLanguage: AppLanguage

    private let strings: [AppLanguage: [String: String]] = [
        .en: [
            "app_name": "AIHandy",
            "lang_system": "Auto (System)",
            "menu_open_ai_chat": "Open AI Chat",
            "menu_settings": "Settings...",
            "menu_quit": "Quit",
            "chat_title": "AI Chat",
            "chat_input_placeholder": "Type a message, Option+Return for new line...",
            "chat_empty": "Start an AI conversation",
            "chat_clear": "Clear",
            "chat_send": "Send",
            "chat_processing": "Thinking...",
            "chat_inject_text": "Send to Chat",
            "qa_title": "Quick Actions",
            "qa_edit_text": "Edit Text",
            "qa_select_action": "Select Action",
            "qa_copy": "Copy",
            "qa_copied": "Copied",
            "qa_close": "Close",
            "qa_replace": "Replace Original",
            "qa_processing": "Processing",
            "qa_no_text": "No text selected",
            "qa_no_text_accessibility": "Unable to get selected text. Grant Accessibility permission in System Settings → Privacy & Security → Accessibility.",
            "qa_authorize": "Authorize",
            "qa_error": "Processing failed",
            "qa_add_custom": "Add Custom",
            "settings_tab_api": "API Config",
            "settings_tab_hotkeys": "Hotkeys",
            "settings_tab_language": "Language",
            "settings_add_config": "Add Config",
            "settings_test": "Test",
            "settings_testing": "Testing...",
            "settings_delete": "Delete",
            "settings_cancel": "Cancel",
            "settings_save": "Save",
            "settings_edit": "Edit",
            "hotkey_recorder": "Record",
            "hotkey_recording": "Press a key...",
            "hotkey_chat": "Open AI Chat",
            "hotkey_quick_action": "Quick Actions",
            "hotkey_apply": "Apply",
            "hotkey_enabled": "Enabled",
            "hotkey_unavailable": "Not Available",
            "api_name": "Name",
            "api_base_url": "API URL",
            "api_model": "Model",
            "api_key": "API Key",
            "api_temperature": "Temperature",
            "api_max_tokens": "Max Tokens",
            "api_add": "Add API",
            "api_edit": "Edit API",
            "api_config_name": "Name",
            "api_test_success": "Connection successful",
            "api_test_fail": "Connection failed",
            "api_missing_key": "Please fill in API Key in settings",
            "api_invalid_url": "Invalid API URL",
            "api_server_error": "Server error",
            "api_response_error": "Response format error",
            "custom_action_title": "Add Custom Action",
            "custom_action_name": "Name",
            "custom_action_system_prompt": "System Prompt",
            "custom_action_user_prompt": "User Prompt (optional, prepended to selected text)",
            "custom_action_cancel": "Cancel",
            "custom_action_save": "Save",
            "action_translate": "Translate",
            "action_polish": "Polish",
            "action_summarize": "Summarize",
            "action_explain_code": "Explain Code",
            "action_expand": "Expand",
            "error_unknown": "Unknown error",
            "settings_add": "Add",
            "settings_no_config": "No configurations",
            "settings_add_first_config": "Add your first config",
            "settings_name": "Name",
            "settings_api_key_placeholder": "API Key (leave blank for local)",
            "settings_api_url": "API URL",
            "settings_model": "Model",
            "settings_temperature": "Temperature: ",
            "settings_max_tokens": "Max Tokens",
            "settings_test_connection": "Test Connection",
            "settings_add_api_config": "Add API Config",
            "settings_accessibility_required": "Accessibility Permission Required",
            "settings_hotkey_registered": "Hotkey Registered",
            "settings_hotkey_unregistered": "Hotkey Not Registered",
            "settings_accessibility_help": "Please add this app in System Settings → Privacy & Security → Accessibility, then click \"Apply\"",
            "settings_quick_actions": "Quick AI Actions",
            "settings_hotkey_help": "Select text and press hotkey to show action panel (translate, polish, summarize, explain code)",
            "hotkey_cancel": "Cancel",
            "hotkey_record": "Record",
            "hotkey_press": "Press a shortcut...",
            "settings_apply": "Apply",
            "settings_new_config": "New Config",
            "settings_enabled": "Enabled",
            "settings_click_to_enable": "Click to Enable",
             "settings_currently_enabled": "Currently Enabled",
             "settings_font_size": "Font Size",
             "chat_you": "You",
             "chat_ai": "AI",
             "settings_chat_font": "Chat Font",
             "font_system": "System",
             "font_rounded": "Rounded",
             "font_serif": "Serif",
             "font_monospace": "Monospace",
             "settings_theme": "Appearance",
             "theme_system": "System",
             "theme_light": "Light",
             "theme_dark": "Dark",
             "lang_auto": "Auto Detect",
             "translation_source": "Source Language",
             "translation_target": "Target Language",
         ],
         .zhHans: [
            "app_name": "AIHandy",
            "lang_system": "跟随系统",
            "menu_open_ai_chat": "打开 AI 对话",
            "menu_settings": "设置...",
            "menu_quit": "退出",
            "chat_title": "AI 对话",
            "chat_input_placeholder": "输入消息，Option+Return 换行...",
            "chat_empty": "输入内容开始 AI 对话",
            "chat_clear": "清除对话",
            "chat_send": "发送",
            "chat_processing": "思考中...",
            "chat_inject_text": "发送到AI对话",
            "qa_title": "AI 快速操作",
            "qa_edit_text": "编辑文本",
            "qa_select_action": "选择操作",
            "qa_copy": "复制",
            "qa_copied": "已复制",
            "qa_close": "关闭",
            "qa_replace": "替换原文",
            "qa_processing": "处理",
            "qa_no_text": "未检测到选中文本",
            "qa_no_text_accessibility": "无法获取选中文本。请在「系统设置 → 隐私与安全性 → 辅助功能」中添加 aifirst",
            "qa_authorize": "授权",
            "qa_error": "处理失败",
            "qa_add_custom": "添加自定义",
            "settings_tab_api": "API 配置",
            "settings_tab_hotkeys": "快捷键",
            "settings_tab_language": "语言",
            "settings_add_config": "添加配置",
            "settings_test": "测试",
            "settings_testing": "测试中...",
            "settings_delete": "删除",
            "settings_cancel": "取消",
            "settings_save": "保存",
            "settings_edit": "编辑",
            "hotkey_recorder": "录制",
            "hotkey_recording": "按下按键...",
            "hotkey_chat": "打开 AI 对话",
            "hotkey_quick_action": "AI 快速操作",
            "hotkey_apply": "应用",
            "hotkey_enabled": "已启用",
            "hotkey_unavailable": "不可用",
            "api_name": "名称",
            "api_base_url": "API 地址",
            "api_model": "模型",
            "api_key": "API Key",
            "api_temperature": "温度",
            "api_max_tokens": "最大 Token",
            "api_add": "添加 API",
            "api_edit": "编辑 API",
            "api_config_name": "名称",
            "api_test_success": "连接成功",
            "api_test_fail": "连接失败",
            "api_missing_key": "请在设置中填写 API Key",
            "api_invalid_url": "API 地址格式不正确",
            "api_server_error": "服务器错误",
            "api_response_error": "响应格式异常",
            "custom_action_title": "添加自定义功能",
            "custom_action_name": "名称",
            "custom_action_system_prompt": "System Prompt",
            "custom_action_user_prompt": "User Prompt（可选，追加在选中文本前）",
            "custom_action_cancel": "取消",
            "custom_action_save": "保存",
            "action_translate": "翻译",
            "action_polish": "润色",
            "action_summarize": "总结",
            "action_explain_code": "解释代码",
            "action_expand": "扩写",
            "error_unknown": "未知错误",
            "settings_add": "添加",
            "settings_no_config": "暂无配置",
            "settings_add_first_config": "添加第一个配置",
            "settings_name": "名称",
            "settings_api_key_placeholder": "API Key（本地模型可留空）",
            "settings_api_url": "API 地址",
            "settings_model": "模型",
            "settings_temperature": "温度: ",
            "settings_max_tokens": "最大 Token",
            "settings_test_connection": "测试连接",
            "settings_add_api_config": "添加 API 配置",
            "settings_accessibility_required": "需要辅助功能权限",
            "settings_hotkey_registered": "快捷键已注册",
            "settings_hotkey_unregistered": "快捷键未注册",
            "settings_accessibility_help": "请在 系统设置 → 隐私与安全性 → 辅助功能 中添加本应用，然后点击\"应用\"按钮",
            "settings_quick_actions": "快速 AI 操作",
            "settings_hotkey_help": "选中文本后按快捷键弹出操作面板（翻译、润色、总结、解释代码）",
            "hotkey_cancel": "取消",
            "hotkey_record": "录制",
            "hotkey_press": "按下快捷键...",
            "settings_apply": "应用",
            "settings_new_config": "新配置",
            "settings_enabled": "已启用",
            "settings_click_to_enable": "点击启用",
            "settings_currently_enabled": "当前启用",
            "settings_font_size": "字体大小",
            "chat_you": "你",
            "chat_ai": "AI",
            "settings_chat_font": "聊天字体",
            "font_system": "系统",
            "font_rounded": "圆体",
            "font_serif": "衬线",
            "font_monospace": "等宽",
            "settings_theme": "外观",
            "theme_system": "跟随系统",
            "theme_light": "浅色",
            "theme_dark": "深色",
            "lang_auto": "自动检测",
            "translation_source": "源语言",
            "translation_target": "目标语言",
        ],
        .zhHant: [
            "app_name": "AIHandy",
            "lang_system": "跟隨系統",
            "menu_open_ai_chat": "開啟 AI 對話",
            "menu_settings": "設定...",
            "menu_quit": "退出",
            "chat_title": "AI 對話",
            "chat_input_placeholder": "輸入訊息，Option+Return 換行...",
            "chat_empty": "輸入內容開始 AI 對話",
            "chat_clear": "清除對話",
            "chat_send": "傳送",
            "chat_processing": "思考中...",
            "chat_inject_text": "傳送到AI對話",
            "qa_title": "AI 快速操作",
            "qa_edit_text": "編輯文字",
            "qa_select_action": "選擇操作",
            "qa_copy": "複製",
            "qa_copied": "已複製",
            "qa_close": "關閉",
            "qa_replace": "取代原文",
            "qa_processing": "處理",
            "qa_no_text": "未偵測到選取文字",
            "qa_no_text_accessibility": "無法獲取選取文字。請在「系統設定 → 私隱與安全性 → 輔助使用」中加入 aifirst",
            "qa_authorize": "授權",
            "qa_error": "處理失敗",
            "qa_add_custom": "新增自訂",
            "settings_tab_api": "API 設定",
            "settings_tab_hotkeys": "快捷鍵",
            "settings_tab_language": "語言",
            "settings_add_config": "新增設定",
            "settings_test": "測試",
            "settings_testing": "測試中...",
            "settings_delete": "刪除",
            "settings_cancel": "取消",
            "settings_save": "儲存",
            "settings_edit": "編輯",
            "hotkey_recorder": "錄製",
            "hotkey_recording": "按下按鍵...",
            "hotkey_chat": "開啟 AI 對話",
            "hotkey_quick_action": "AI 快速操作",
            "hotkey_apply": "套用",
            "hotkey_enabled": "已啟用",
            "hotkey_unavailable": "不可用",
            "api_name": "名稱",
            "api_base_url": "API 位址",
            "api_model": "模型",
            "api_key": "API Key",
            "api_temperature": "溫度",
            "api_max_tokens": "最大 Token",
            "api_add": "新增 API",
            "api_edit": "編輯 API",
            "api_config_name": "名稱",
            "api_test_success": "連線成功",
            "api_test_fail": "連線失敗",
            "api_missing_key": "請在設定中填入 API Key",
            "api_invalid_url": "API 位址格式不正確",
            "api_server_error": "伺服器錯誤",
            "api_response_error": "回應格式異常",
            "custom_action_title": "新增自訂功能",
            "custom_action_name": "名稱",
            "custom_action_system_prompt": "System Prompt",
            "custom_action_user_prompt": "User Prompt（可選，附加在選取文字前）",
            "custom_action_cancel": "取消",
            "custom_action_save": "儲存",
            "action_translate": "翻譯",
            "action_polish": "潤色",
            "action_summarize": "總結",
            "action_explain_code": "解釋程式碼",
            "action_expand": "擴寫",
            "error_unknown": "未知錯誤",
            "settings_add": "新增",
            "settings_no_config": "暫無設定",
            "settings_add_first_config": "新增第一個設定",
            "settings_name": "名稱",
            "settings_api_key_placeholder": "API Key（本地模型可留空）",
            "settings_api_url": "API 位址",
            "settings_model": "模型",
            "settings_temperature": "溫度: ",
            "settings_max_tokens": "最大 Token",
            "settings_test_connection": "測試連線",
            "settings_add_api_config": "新增 API 設定",
            "settings_accessibility_required": "需要輔助使用權限",
            "settings_hotkey_registered": "快捷鍵已註冊",
            "settings_hotkey_unregistered": "快捷鍵未註冊",
            "settings_accessibility_help": "請在系統設定→私隱與安全性→輔助使用中加入本應用，然後點擊「套用」按鈕",
            "settings_quick_actions": "快速 AI 操作",
            "settings_hotkey_help": "選取文字後按快捷鍵彈出操作面板（翻譯、潤色、總結、解釋程式碼）",
            "hotkey_cancel": "取消",
            "hotkey_record": "錄製",
            "hotkey_press": "按下快捷鍵...",
            "settings_apply": "套用",
            "settings_new_config": "新設定",
            "settings_enabled": "已啟用",
            "settings_click_to_enable": "點擊啟用",
            "settings_currently_enabled": "目前啟用",
            "settings_font_size": "字型大小",
            "chat_you": "你",
            "chat_ai": "AI",
            "settings_chat_font": "聊天字型",
            "font_system": "系統",
            "font_rounded": "圓體",
            "font_serif": "襯線",
            "font_monospace": "等寬",
            "settings_theme": "外觀",
            "theme_system": "跟隨系統",
            "theme_light": "淺色",
             "theme_dark": "深色",
             "lang_auto": "自動偵測",
             "translation_source": "來源語言",
             "translation_target": "目標語言",
         ],
    ]

    private init() {
        let saved = UserDefaults.standard.string(forKey: "app_language")
        _currentLanguage = AppLanguage(rawValue: saved ?? "") ?? .system
    }

    func tr(_ key: String) -> String {
        _ = _currentLanguage
        let lang = _currentLanguage.effectiveLanguage
        return strings[lang]?[key] ?? strings[.en]?[key] ?? key
    }
}
